version: "3.8"

services:
  web:
    build: .
    command: gunicorn hospital_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build: .
    command: celery -A hospital_backend worker --pool=solo -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    ports:
      - "6380:6379"
